//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AllOdds
{
    using System;
    using System.Collections.Generic;
    
    public partial class Events
    {
        public long event_id { get; set; }
        public string type { get; set; }
        public string minute { get; set; }
        public string team { get; set; }
        public Nullable<long> player_id { get; set; }
        public string result { get; set; }
        public long match_id { get; set; }
        public Nullable<long> assist_id { get; set; }

        public string player_name { get; set; }
        public string assist_name { get; set; }


        public virtual Matches Matches { get; set; }
        public virtual Players Players { get; set; }
        public virtual Players Players1 { get; set; }
    }
}
